### PR TITLE
support iojs

### PR DESCRIPTION
**Pull request by EndangeredMassa**
Adapted from: https://github.com/groupon-testium/testium/pull/148/files

### CODE REVIEW

**Comment by jkrems** [comment]
:+1:

**Comment by EndangeredMassa** [comment]
Using: io.js v2.0.1

```
$ npm install
npm WARN prefer global coffee-script@1.9.1 should be installed with -g
 
> http-sync@0.1.1 install /home/sean/source/testium/node_modules/webdriver-http-sync/node_modules/http-sync
> node-gyp rebuild

make: Entering directory '/home/sean/source/testium/node_modules/webdriver-http-sync/node_modules/http-sync/build'
  CXX(target) Release/obj.target/curllib/curllib.o
In file included from ../node_modules/nan/nan_new.h:190:0,
                 from ../node_modules/nan/nan.h:74,
                 from ../curllib.cc:8:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::Signature>::return_t NanIntern::Factory<v8::Signature>::New(NanIntern::Factory<v8::Signature>::FTH, int, NanIntern::Factory<v8::Signature>::FTH*)’:
../node_modules/nan/nan_implementation_12_inl.h:181:76: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)’
   return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                            ^
../node_modules/nan/nan_implementation_12_inl.h:181:76: note: candidate is:
In file included from /home/sean/.node-gyp/2.0.1/src/node.h:42:0,
                 from ../node_modules/nan/nan.h:24,
                 from ../curllib.cc:8:
/home/sean/.node-gyp/2.0.1/deps/v8/include/v8.h:4188:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/home/sean/.node-gyp/2.0.1/deps/v8/include/v8.h:4188:27: note:   candidate expects 2 arguments, 4 provided
curllib.target.mk:86: recipe for target 'Release/obj.target/curllib/curllib.o' failed
make: *** [Release/obj.target/curllib/curllib.o] Error 1
make: Leaving directory '/home/sean/source/testium/node_modules/webdriver-http-sync/node_modules/http-sync/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/sean/.nvm/versions/io.js/v2.0.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Linux 3.19.0-16-generic
gyp ERR! command "/home/sean/.nvm/versions/io.js/v2.0.1/bin/iojs" "/home/sean/.nvm/versions/io.js/v2.0.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/sean/source/testium/node_modules/webdriver-http-sync/node_modules/http-sync
gyp ERR! node -v v2.0.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.19.0-16-generic
npm ERR! argv "/home/sean/.nvm/versions/io.js/v2.0.1/bin/iojs" "/home/sean/.nvm/versions/io.js/v2.0.1/bin/npm" "install"
npm ERR! node v2.0.1
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE

npm ERR! http-sync@0.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the http-sync@0.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the http-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls http-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sean/source/testium/npm-debug.log
```

**Comment by jkrems** [comment]
My best guess: `http-sync` needs a nan bump.

**Comment by EndangeredMassa** [comment]
That seems to fix it. PR: https://github.com/dhruvbird/http-sync/pull/41

**Comment by jkrems** [comment]
I'm running the latest testium on iojs-v2. Can this be closed?

**Comment by EndangeredMassa** [comment]
Closing in favor of: https://github.com/groupon/testium/pull/165

**Pull request closed without merging**
